// <auto-generated />
using System;
using DemoAsyncApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoAsyncApi.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoAsyncApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc")
                        .HasMaxLength(5000);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Demo_User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Desc = "User Desc ...",
                            FullName = "User01",
                            Username = "User01"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Desc = "User Desc ...",
                            FullName = "User02",
                            Username = "User02"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Desc = "User Desc ...",
                            FullName = "User03",
                            Username = "User03"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Desc = "User Desc ...",
                            FullName = "User04",
                            Username = "User04"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Desc = "User Desc ...",
                            FullName = "User05",
                            Username = "User05"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Desc = "User Desc ...",
                            FullName = "User06",
                            Username = "User06"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Desc = "User Desc ...",
                            FullName = "User07",
                            Username = "User07"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Desc = "User Desc ...",
                            FullName = "User08",
                            Username = "User08"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Desc = "User Desc ...",
                            FullName = "User09",
                            Username = "User09"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Desc = "User Desc ...",
                            FullName = "User10",
                            Username = "User10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Desc = "User Desc ...",
                            FullName = "User11",
                            Username = "User11"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Desc = "User Desc ...",
                            FullName = "User12",
                            Username = "User12"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Desc = "User Desc ...",
                            FullName = "User13",
                            Username = "User13"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Desc = "User Desc ...",
                            FullName = "User14",
                            Username = "User14"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Desc = "User Desc ...",
                            FullName = "User15",
                            Username = "User15"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Desc = "User Desc ...",
                            FullName = "User16",
                            Username = "User16"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Desc = "User Desc ...",
                            FullName = "User17",
                            Username = "User17"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Desc = "User Desc ...",
                            FullName = "User18",
                            Username = "User18"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Desc = "User Desc ...",
                            FullName = "User19",
                            Username = "User19"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Desc = "User Desc ...",
                            FullName = "User20",
                            Username = "User20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
